"""Take a JSON dump of the MuddyChildren.tla state space and analyze childrens' knowledge.

First checkout https://github.com/will62794/tlaplus/commits/multi-inv-checking-et-al/
this is Will Schultz's branch of TLC that can dump the state space to JSON. (Standard TLC can only
dump traces to JSON, not the whole state space, see https://github.com/tlaplus/tlaplus/issues/1073).
Build according to https://github.com/tlaplus/tlaplus/blob/master/DEVELOPING.md
On my Mac:
  brew install openjdk@11 ant
  cd tlatools/org.lamport.tlatools
  export PATH=/opt/homebrew/Cellar/openjdk@11/11.0.28/bin/:$PATH
  export JAVA_HOME=/opt/homebrew/Cellar/openjdk@11/11.0.28
  # Don't build the compile-test target, it fails.
  ant -f customBuild.xml info compile dist
"""
import json
import subprocess

import networkx as nx


def run_tlc():
    """Run TLC on the given specification file."""
    subprocess.check_call([
        "java", "-jar",
        "/Users/emptysquare/co/multi-inv-checking-et-al/tlatools/org.lamport.tlatools/"
        "dist/tla2tools.jar",
        "-deadlock",
        "MuddyChildren.tla",
        "-dump", "json", "MuddyChildren",
        "-dump", "dot", "MuddyChildren",
    ], env={
        "JAVA_HOME": "/opt/homebrew/Cellar/openjdk@11/11.0.28/bin/",
        "PATH": "/opt/homebrew/Cellar/openjdk@11/11.0.28/bin/:$PATH"
    })

    subprocess.check_call([
        "dot", "-Tpdf", "MuddyChildren.dot", "-o", "MuddyChildren.pdf"
    ])


# Adapted from https://github.com/mongodb-labs/vldb25-dist-txns
def parse_json_state_graph():
    """ Parse the JSON state graph generated by TLC. """
    G = nx.DiGraph()

    # Stores mapping from graph edges to the action + parameters associated with
    # that transition edge.
    edge_actions = {}

    states_fpath = "MuddyChildren-states.json"
    edges_fpath = "MuddyChildren-edges.json"

    fgraph = open(edges_fpath)
    json_graph = json.load(fgraph)
    for edge in json_graph["edges"]:
        G.add_edge(edge["from"], edge["to"])
        edge_actions[(edge["from"], edge["to"])] = edge

    fgraph = open(states_fpath)
    json_graph = json.load(fgraph)
    node_map = {}
    for node in json_graph["states"]:
        node_map[node["fp"]] = node["val"]

    print("# Original graph:")
    print(len(G.nodes()), "nodes")
    print(len(G.edges()), "edges")

    return (G, node_map, edge_actions)


if __name__ == "__main__":
    run_tlc()
    G, node_map, edge_actions = parse_json_state_graph()
